[common]
seed = 42  # random seed for initializing MTP parameters etc.

[configurations]
training = 'training.cfg'

[potentials]
initial = 'initial.mtp'
final = 'final.mtp'

[loss]  # setting for the loss function
energy_weight = 1.0
forces_weight = 0.01
stress_weight = 0.001

# optimization steps

# style 1: simple
# steps = ['Nelder-Mead', 'BFGS']

# style 2: sophisticated
# "optimized" specifies which parameters are optimized at the step.
[[steps]]
method = 'Nelder-Mead'
optimized = ['species_coeffs', 'radial_coeffs', 'moment_coeffs']
[steps.kwargs]
tol = 1e-7
[steps.kwargs.options]
maxiter = 1000

[[steps]]
method = 'BFGS'
optimized = ['species_coeffs', 'radial_coeffs', 'moment_coeffs']
